name: Update Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js
        env:
          API_KEY: ${{ secrets.API_KEY }}
          
      - name: Create commit
        run: |
              git config user.name "suyash-thakur"
              git config user.email "suyashthakur910@gmail.com"
              git add README.md
              git commit -m "Update README"
              git push
